apiVersion: v1
kind: Pod
metadata:
  annotations: 
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: jmeter
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: 30Mi
        cpu: 300m
    ports:
      - containerPort: 80
