apiVersion: v1
kind: Pod
metadata:
  annotations: 
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: jmeter
  
spec:
  containers:
  - name: "nginx"
    image: nginx:latest
    resources:
      limits:
        memory: memorylimit
        cpu: cpulimit
    
    ports:
      - containerPort: 80
      
    tty: true
  - command:
    - "cat"
