apiVersion: v1
kind: Pod
metadata:
  annotations: 
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: jmeter
  
spec:
  containers:
  - name: jmeter
    image: justb4/jmeter:5.4
    resources:
      limits:
        memory: memorylimit
        cpu: cpulimit
    ports:
      - containerPort: 80
    

  
  
