project_name = "gcp0tohero"
region = "us-central1"
zone = "us-central1-c"
cred_file = "/home/shakeer/gcp0tohero-7d764dbc5ba3.json"
network_name = "terraform-gcp0tohero-gke"
bucket_name = "gcp0toherostatefile-5858"
